obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_inflation: 0.01
#robot_radius: 0.175
inflation_radius: 1.0
cost_scaling_factor: 3.0
map_type: costmap
#transform_tolerance: 1
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
