# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
