global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

  update_frequency: 10.0
  publish_frequency: 10.0

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
