shutdown_costmaps: false

oscillation_distance: 0.2
oscillation_timeout: 10.0

controller_frequency: 10.0
controller_patience: 15.0

planner_frequency: 5.0
planner_patience: 5.0
max_planning_retries: -1
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/TebLocalPlannerROS"
