# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.9 #1.032
    has_acceleration_limits: true
    max_acceleration: 1
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.4 #0.452
    has_acceleration_limits: true
    max_acceleration: 1
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.5 #0.618
    has_acceleration_limits: true
    max_acceleration: 1
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.4 #0.494
    has_acceleration_limits: true
    max_acceleration: 1
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.4 #0.494
    has_acceleration_limits: true
    max_acceleration: 1
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.2 #1.344
    has_acceleration_limits: true
    max_acceleration: 1
